version: '3'
services:

  #Laravel App
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: hakase-labs/laravel
    container_name: api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /var/www/apitest
    volumes:
      - ./:/var/www/apitest
    networks:
      - mynet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9090:9090"
    volumes:
      - ./:/var/www/apitest
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - mynet

  #MySQL Service
  api-db:
    image: mysql:5.7
    container_name: api0db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local