version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/var/www/apitest
    depends_on:
      - apidb
    ports:
      - "9090:80"
    networks:
      - apitest-network
  
  api-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - apitest-network
  
networks:
  apitest-network:

volumes:
  dbdata:
